"""add users.session_version for session revocation

Revision ID: 2d9f3b20045f
Revises: 38297b707b89
Create Date: 2026-08-18 11:00:41.715000

Milestone 09. Adds the server-side state that makes logout actually revoke a
session.

Before this column existed, the session was a stateless signed cookie holding
only a user id, so `session.clear()` on logout cleared the browser's copy but
could not invalidate a copy captured beforehand -- that copy kept
authenticating until the 8-hour lifetime elapsed (verified in M08, see
docs/SECURITY.md §6).

`login_user` now stamps the session with this counter and `logout_user`
increments it, so every session issued before a logout stops validating.

Written by hand, not autogenerated: autogenerate reports the pre-existing
CHECK constraints as changed on every run (the long-standing false positive
documented in 8d5ba0171efe and d8f3bfd0e2a9), so its output cannot be used
unreviewed here.

`server_default="0"` is required, not cosmetic: the column is NOT NULL and
existing rows must be backfilled by the database as the column is added.
Sessions issued *before* this migration carry no version at all, so they fail
the comparison and are refused -- every pre-existing login is invalidated on
deploy, which is the intended fail-closed behaviour.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9f3b20045f'
down_revision = '38297b707b89'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('session_version', sa.Integer(), nullable=False, server_default=sa.text('0'))
        )


def downgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_version')
