"""widen audit event allow-list for order status events

Revision ID: 38297b707b89
Revises: d8f3bfd0e2a9
Create Date: 2026-08-17 11:14:39.590721

Milestone 05 adds two `AuditEvent` members (`order_status_changed`,
`order_status_change_rejected` -- see app/models/audit_log.py), so
`ck_audit_logs_event_type`'s allow-list must be widened or every staff
status change fails with an IntegrityError at runtime.

Written by hand, not autogenerated. `flask db revision` (no `--autogenerate`)
was used deliberately: autogenerate reports this constraint -- and several
unrelated ones -- as "changed" on *every* run regardless of whether anything
actually changed, so its output cannot distinguish a real widening from a
false positive. That ambiguity is precisely what produced the M04 bug this
project already hit once (see d8f3bfd0e2a9's own upgrade() and
docs/DATABASE.md). Only the enum whose members actually changed is touched
here.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38297b707b89'
down_revision = 'd8f3bfd0e2a9'
branch_labels = None
depends_on = None


# The M04 allow-list, i.e. what downgrade() must restore.
_EVENTS_BEFORE = (
    'register_success', 'login_success', 'login_failure', 'login_rate_limited', 'logout',
    'category_created', 'category_updated', 'category_deactivated',
    'menu_item_created', 'menu_item_updated', 'menu_item_availability_changed', 'ingredient_changed',
    'order_created', 'order_creation_failed',
)

_EVENTS_AFTER = _EVENTS_BEFORE + ('order_status_changed', 'order_status_change_rejected')


def _check_sql(events: tuple[str, ...]) -> str:
    return "event_type IN (" + ", ".join(f"'{e}'" for e in events) + ")"


def upgrade():
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_audit_logs_event_type', type_='check')
        batch_op.create_check_constraint('ck_audit_logs_event_type', _check_sql(_EVENTS_AFTER))


def downgrade():
    # Rows written by M05 would violate the narrower constraint, so drop them
    # first -- an audit row for an event type the schema no longer knows about
    # cannot be represented, and silently failing the downgrade is worse.
    op.execute(
        "DELETE FROM audit_logs WHERE event_type IN "
        "('order_status_changed', 'order_status_change_rejected')"
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_audit_logs_event_type', type_='check')
        batch_op.create_check_constraint('ck_audit_logs_event_type', _check_sql(_EVENTS_BEFORE))
