"""add users.staff_approved and staff-approval audit events

Revision ID: 7c4e1a9b52d3
Revises: 2d9f3b20045f
Create Date: 2026-09-27 12:00:00.000000

Phase 3. Staff accounts now need explicit administrator approval before they
can sign in (app/utils/authorization.py::get_current_user).

Existing accounts
-----------------
The column is added with ``server_default=false``, so every row starts
unapproved -- which is harmless for customers and admins, because the flag is
only consulted for ``role = 'staff'``.

Existing STAFF rows are then approved explicitly. Before this revision the
application had no route that could create a staff account: the only ways to
get one were ``scripts/seed_demo.py`` or a direct database write, both of which
already require operator access. Every pre-existing staff account was therefore
provisioned by a trusted operator, and locking them out on deploy would break a
working installation for no security gain. Accounts created *after* this
revision -- through the new public staff sign-up -- start pending.

Written by hand, not autogenerated, for the reason documented in 2d9f3b20045f:
autogenerate reports the pre-existing CHECK constraints as changed on every
run. The audit allow-list is widened the same way 38297b707b89 did it.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4e1a9b52d3'
down_revision = '2d9f3b20045f'
branch_labels = None
depends_on = None


# The allow-list as 38297b707b89 left it, i.e. what downgrade() must restore.
_EVENTS_BEFORE = (
    'register_success', 'login_success', 'login_failure', 'login_rate_limited', 'logout',
    'category_created', 'category_updated', 'category_deactivated',
    'menu_item_created', 'menu_item_updated', 'menu_item_availability_changed', 'ingredient_changed',
    'order_created', 'order_creation_failed',
    'order_status_changed', 'order_status_change_rejected',
)

_NEW_EVENTS = ('staff_registered', 'staff_approved', 'staff_approval_revoked')
_EVENTS_AFTER = _EVENTS_BEFORE + _NEW_EVENTS


def _check_sql(events: tuple[str, ...]) -> str:
    return "event_type IN (" + ", ".join(f"'{e}'" for e in events) + ")"


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('staff_approved', sa.Boolean(), nullable=False, server_default=sa.false())
        )
    # Grandfather operator-provisioned staff (see module docstring).
    users = sa.table('users', sa.column('role', sa.String), sa.column('staff_approved', sa.Boolean))
    op.execute(users.update().where(users.c.role == 'staff').values(staff_approved=True))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_audit_logs_event_type', type_='check')
        batch_op.create_check_constraint('ck_audit_logs_event_type', _check_sql(_EVENTS_AFTER))


def downgrade():
    # Rows for event types the narrower constraint does not know cannot be
    # represented after downgrade; drop them rather than fail half-way.
    op.execute(
        "DELETE FROM audit_logs WHERE event_type IN ("
        + ", ".join(f"'{e}'" for e in _NEW_EVENTS) + ")"
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_audit_logs_event_type', type_='check')
        batch_op.create_check_constraint('ck_audit_logs_event_type', _check_sql(_EVENTS_BEFORE))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('staff_approved')
