"""Add menu data layer and fix missing enum CHECK constraints

Revision ID: 8d5ba0171efe
Revises: abf997064564
Create Date: 2026-08-16 20:26:36.838300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5ba0171efe'
down_revision = 'abf997064564'
branch_labels = None
depends_on = None


def upgrade():
    # --- manual: retrofit CHECK constraints missing since M02 -----------
    # `sa.Enum(native_enum=False)` does not emit a database-level CHECK
    # constraint unless `create_constraint=True` is also passed -- that was
    # missing on `users.role` and `audit_logs.event_type` when M02 first
    # created them, so both columns have been bare, unconstrained VARCHARs
    # in every environment until now. Caught while building this migration,
    # not from re-reading the M02 code -- see app/models/enums.py. Alembic
    # autogenerate does not detect this class of change on its own (it
    # produced no diff for either column), so both ADD CONSTRAINTs below are
    # hand-written, not generated.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_users_role', "role IN ('admin', 'staff', 'customer')")

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_check_constraint(
            'ck_audit_logs_event_type',
            "event_type IN ("
            "'register_success', 'login_success', 'login_failure', 'login_rate_limited', 'logout', "
            "'category_created', 'category_updated', 'category_deactivated', "
            "'menu_item_created', 'menu_item_updated', 'menu_item_availability_changed', 'ingredient_changed'"
            ")",
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dietary_preference', sa.Enum('vegetarian', 'vegan', 'eggetarian', 'non_vegetarian', name='ck_customer_preferences_dietary_preference', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('cuisine_preference', sa.Enum('indian', 'chinese', 'italian', 'continental', 'mexican', 'thai', 'multi_cuisine', 'other', name='ck_customer_preferences_cuisine_preference', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('spice_preference', sa.Enum('none', 'mild', 'medium', 'hot', 'extra_hot', name='ck_customer_preferences_spice_preference', native_enum=False, create_constraint=True, length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cuisine', sa.Enum('indian', 'chinese', 'italian', 'continental', 'mexican', 'thai', 'multi_cuisine', 'other', name='ck_menu_items_cuisine', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('spice_level', sa.Enum('none', 'mild', 'medium', 'hot', 'extra_hot', name='ck_menu_items_spice_level', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('dietary_type', sa.Enum('vegetarian', 'vegan', 'eggetarian', 'non_vegetarian', name='ck_menu_items_dietary_type', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_menu_items_price_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.create_index('ix_menu_items_category_available', ['category_id', 'is_available'], unique=False)

    op.create_table('menu_item_ingredients',
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id', 'ingredient_id')
    )
    with op.batch_alter_table('menu_item_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_item_ingredients_ingredient_id'), ['ingredient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_item_ingredients_ingredient_id'))

    op.drop_table('menu_item_ingredients')
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index('ix_menu_items_category_available')

    op.drop_table('menu_items')
    op.drop_table('customer_preferences')
    op.drop_table('ingredients')
    op.drop_table('categories')
    # ### end Alembic commands ###

    # --- manual: reverse the CHECK-constraint retrofit above -------------
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_audit_logs_event_type', type_='check')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_users_role', type_='check')
