"""add restaurant tables, reservations, order source/table, cancellation record, served status

Revision ID: b5e2f8c41a07
Revises: 7c4e1a9b52d3
Create Date: 2026-09-29 12:00:00.000000

Milestone 10 (brief "M08 -- Restaurant Operations, Customer Cancellation &
Sales Analytics").

- ``restaurant_tables``: new table with a status allow-list CHECK.
- ``orders.source``: NOT NULL with ``server_default 'online'``, so every
  existing order is backfilled as ONLINE -- true, since until now the web
  checkout was the only way an order could be created.
- ``orders.table_id``: nullable; ``ck_orders_source_table`` requires it for
  dine-in and forbids it otherwise. Existing rows (online, NULL) satisfy it.
- ``orders.cancelled_at / cancelled_by_id / cancellation_actor /
  cancellation_reason``: nullable. Orders cancelled before this revision keep
  NULLs -- who cancelled them was never recorded, and inventing it would be
  worse than admitting it.
- ``reservations``: new table; double-booking is prevented by the unique
  index ``uq_reservations_table_slot`` (see app/models/reservation.py).
- ``orders.status`` gains ``served`` (READY -> SERVED -> COMPLETED for
  dine-in). Downgrade maps any ``served`` row back to ``ready`` -- the closest
  state the narrower constraint can represent -- rather than fail.
- Audit allow-list widened for the table and reservation events.

Written by hand (not autogenerated) for the reason recorded in 2d9f3b20045f.
The enum columns are added as plain VARCHARs plus an explicit, named CHECK:
``op.add_column`` does not reliably emit an Enum's CHECK on MySQL, and naming
it here keeps the constraint identical to what ``enum_column()`` produces.
No existing data is modified except the backfill default above.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e2f8c41a07'
down_revision = '7c4e1a9b52d3'
branch_labels = None
depends_on = None


_EVENTS_BEFORE = (
    'register_success', 'login_success', 'login_failure', 'login_rate_limited', 'logout',
    'category_created', 'category_updated', 'category_deactivated',
    'menu_item_created', 'menu_item_updated', 'menu_item_availability_changed', 'ingredient_changed',
    'order_created', 'order_creation_failed',
    'order_status_changed', 'order_status_change_rejected',
    'staff_registered', 'staff_approved', 'staff_approval_revoked',
)
_NEW_EVENTS = (
    'table_created', 'table_updated', 'table_status_changed',
    'reservation_created', 'reservation_status_changed',
)
_STATUSES_BEFORE = ('pending', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled')
_STATUSES_AFTER = ('pending', 'confirmed', 'preparing', 'ready', 'served', 'completed', 'cancelled')
_EVENTS_AFTER = _EVENTS_BEFORE + _NEW_EVENTS


def _in(column: str, values: tuple[str, ...]) -> str:
    return f"{column} IN (" + ", ".join(f"'{v}'" for v in values) + ")"


def upgrade():
    op.create_table(
        'restaurant_tables',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=40), nullable=False),
        sa.Column('capacity', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=16), server_default='available', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.CheckConstraint('capacity >= 1 AND capacity <= 50', name='ck_restaurant_tables_capacity_range'),
        sa.CheckConstraint(
            _in('status', ('available', 'occupied', 'reserved', 'cleaning', 'out_of_service')),
            name='ck_restaurant_tables_status',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )

    op.create_table(
        'reservations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('table_id', sa.Integer(), nullable=False),
        sa.Column('reservation_date', sa.Date(), nullable=False),
        sa.Column('reservation_time', sa.Time(), nullable=False),
        sa.Column('guest_count', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=16), server_default='confirmed', nullable=False),
        sa.Column('holds_slot', sa.Boolean(), nullable=True),
        sa.Column('reserved_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.CheckConstraint('guest_count >= 1', name='ck_reservations_guest_count_positive'),
        sa.CheckConstraint(
            _in('status', ('confirmed', 'completed', 'no_show', 'cancelled')), name='ck_reservations_status'
        ),
        sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'table_id', 'reservation_date', 'reservation_time', 'holds_slot', name='uq_reservations_table_slot'
        ),
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index('ix_reservations_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_reservations_date_time', ['reservation_date', 'reservation_time'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('ck_orders_status', type_='check')
        batch_op.create_check_constraint('ck_orders_status', _in('status', _STATUSES_AFTER))
        batch_op.add_column(sa.Column('source', sa.String(length=16), server_default='online', nullable=False))
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_actor', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(
            'fk_orders_table_id_restaurant_tables', 'restaurant_tables', ['table_id'], ['id'], ondelete='RESTRICT'
        )
        batch_op.create_foreign_key(
            'fk_orders_cancelled_by_id_users', 'users', ['cancelled_by_id'], ['id'], ondelete='RESTRICT'
        )
        batch_op.create_index('ix_orders_table_id', ['table_id'], unique=False)
        batch_op.create_index('ix_orders_created_at', ['created_at'], unique=False)
        batch_op.create_check_constraint(
            'ck_orders_source', _in('source', ('dine_in', 'takeaway', 'delivery', 'online'))
        )
        batch_op.create_check_constraint(
            'ck_orders_cancellation_actor', _in('cancellation_actor', ('customer', 'staff', 'admin'))
        )
        batch_op.create_check_constraint(
            'ck_orders_source_table',
            "(source = 'dine_in' AND table_id IS NOT NULL) OR (source <> 'dine_in' AND table_id IS NULL)",
        )

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_audit_logs_event_type', type_='check')
        batch_op.create_check_constraint('ck_audit_logs_event_type', _in('event_type', _EVENTS_AFTER))


def downgrade():
    # Audit rows for events the narrower constraint does not know cannot be
    # represented after downgrade (same policy as 7c4e1a9b52d3).
    op.execute("DELETE FROM audit_logs WHERE " + _in('event_type', _NEW_EVENTS))
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_audit_logs_event_type', type_='check')
        batch_op.create_check_constraint('ck_audit_logs_event_type', _in('event_type', _EVENTS_BEFORE))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('ck_orders_source_table', type_='check')
        batch_op.drop_constraint('ck_orders_cancellation_actor', type_='check')
        batch_op.drop_constraint('ck_orders_source', type_='check')
        # Foreign keys before indexes: MySQL refuses to drop an index a
        # foreign key still depends on (error 1553) -- found by running this
        # downgrade against MySQL 8.0.46; SQLite's batch rebuild never noticed.
        batch_op.drop_constraint('fk_orders_cancelled_by_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_orders_table_id_restaurant_tables', type_='foreignkey')
        batch_op.drop_index('ix_orders_created_at')
        batch_op.drop_index('ix_orders_table_id')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancellation_actor')
        batch_op.drop_column('cancelled_by_id')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('table_id')
        batch_op.drop_column('source')

    op.execute("UPDATE orders SET status = 'ready' WHERE status = 'served'")
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('ck_orders_status', type_='check')
        batch_op.create_check_constraint('ck_orders_status', _in('status', _STATUSES_BEFORE))

    # drop_table removes the table's indexes with it; dropping
    # ix_reservations_user_id first fails on MySQL (error 1553: the user_id
    # foreign key still needs it).
    op.drop_table('reservations')
    op.drop_table('restaurant_tables')
