"""add cart order tables

Revision ID: d8f3bfd0e2a9
Revises: 8d5ba0171efe
Create Date: 2026-08-17 10:26:01.463497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f3bfd0e2a9'
down_revision = '8d5ba0171efe'
branch_labels = None
depends_on = None


def upgrade():
    # Autogenerate also reported drop_constraint/create_check_constraint on
    # ck_customer_preferences_*, ck_menu_items_*, and ck_users_role -- the
    # same CHECK-constraint diffing false positive documented at the top of
    # 8d5ba0171efe's own upgrade(). Nothing about those columns changed in
    # this milestone; those three spurious drop/recreate pairs were removed
    # by hand rather than applied.
    #
    # ck_audit_logs_event_type is different: AuditEvent gained two real
    # members this milestone (ORDER_CREATED, ORDER_CREATION_FAILED -- see
    # app/models/audit_log.py), so its CHECK constraint's allow-list is
    # genuinely stale and must be widened, same retrofit pattern as
    # 8d5ba0171efe used to add this constraint in the first place. Caught by
    # a live checkout in manual browser testing raising IntegrityError, not
    # by autogenerate -- it reports this constraint as "changed" on every
    # run regardless (the same textual-diff limitation), so its output
    # alone cannot distinguish a real change here from the three false
    # positives above.
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_audit_logs_event_type', type_='check')
        batch_op.create_check_constraint(
            'ck_audit_logs_event_type',
            "event_type IN ("
            "'register_success', 'login_success', 'login_failure', 'login_rate_limited', 'logout', "
            "'category_created', 'category_updated', 'category_deactivated', "
            "'menu_item_created', 'menu_item_updated', 'menu_item_availability_changed', 'ingredient_changed', "
            "'order_created', 'order_creation_failed'"
            ")",
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled', name='ck_orders_status', native_enum=False, create_constraint=True, length=16), server_default='pending', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('subtotal >= 0', name='ck_orders_subtotal_nonnegative'),
    sa.CheckConstraint('total >= 0', name='ck_orders_total_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('item_name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('line_total >= 0', name='ck_order_items_line_total_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity_positive'),
    sa.CheckConstraint('unit_price_snapshot >= 0', name='ck_order_items_unit_price_nonnegative'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_menu_item_id'), ['menu_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_menu_item_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_user_created')

    op.drop_table('orders')
    # ### end Alembic commands ###

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_audit_logs_event_type', type_='check')
        batch_op.create_check_constraint(
            'ck_audit_logs_event_type',
            "event_type IN ("
            "'register_success', 'login_success', 'login_failure', 'login_rate_limited', 'logout', "
            "'category_created', 'category_updated', 'category_deactivated', "
            "'menu_item_created', 'menu_item_updated', 'menu_item_availability_changed', 'ingredient_changed'"
            ")",
        )
