"""SQLAlchemy models.

Every model module must be imported here so it registers on
``db.metadata`` -- a model that is never imported is silently missing from
every autogenerated migration. Import order matters where one module's
class is referenced by another (e.g. ``MenuItem`` needs ``Ingredient`` and
``MenuItemIngredient`` already defined for its ``secondary=`` relationship).
"""

from app.models.audit_log import AuditEvent, AuditLog
from app.models.category import Category
from app.models.customer_preference import CustomerPreference
from app.models.ingredient import Ingredient
from app.models.menu_item_ingredient import MenuItemIngredient
from app.models.menu_item import MenuItem
from app.models.restaurant_table import RestaurantTable, TableStatus
from app.models.order import CancellationActor, Order, OrderItem, OrderSource, OrderStatus
from app.models.payment import Payment, PaymentMethod
from app.models.reservation import Reservation, ReservationStatus
from app.models.user import Role, User

__all__ = [
    "AuditEvent",
    "CancellationActor",
    "AuditLog",
    "Category",
    "CustomerPreference",
    "Ingredient",
    "MenuItem",
    "MenuItemIngredient",
    "Order",
    "OrderItem",
    "OrderSource",
    "OrderStatus",
    "Payment",
    "PaymentMethod",
    "Reservation",
    "ReservationStatus",
    "RestaurantTable",
    "Role",
    "TableStatus",
    "User",
]
