"""Customer table reservations -- deliberately separate from ``Order``.

Two different times live here and must never be confused:

- ``reservation_date`` + ``reservation_time`` -- the slot the customer wants
  the table for (restaurant-local wall-clock, a booking schedule).
- ``reserved_at`` -- when the booking was actually made. Server-generated by
  the database (``server_default=now()``), never accepted from a client.

**Double-booking** is prevented by the database, not by a check-then-insert:
``uq_reservations_table_slot`` is UNIQUE over (table, date, slot start,
``holds_slot``). ``holds_slot`` is TRUE while a reservation occupies its slot
and NULL once cancelled; SQL treats NULLs as distinct in a unique index (both
MySQL and SQLite), so a cancelled booking releases the slot while two live
ones for the same slot can never both commit -- the second concurrent INSERT
fails with an IntegrityError. Slots are fixed, non-overlapping windows (see
``app/services/reservations.py``), so "conflicting time" and "same slot" are
the same thing and one unique index covers both.
"""

from __future__ import annotations

import enum
from datetime import date, datetime, time

import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.extensions import db
from app.models.enums import enum_column


class ReservationStatus(str, enum.Enum):
    CONFIRMED = "confirmed"  # created confirmed: availability is checked on booking
    COMPLETED = "completed"
    NO_SHOW = "no_show"
    CANCELLED = "cancelled"


class Reservation(db.Model):
    __tablename__ = "reservations"
    __table_args__ = (
        sa.UniqueConstraint(
            "table_id", "reservation_date", "reservation_time", "holds_slot", name="uq_reservations_table_slot"
        ),
        sa.CheckConstraint("guest_count >= 1", name="ck_reservations_guest_count_positive"),
        # Backs the staff list (by date) -- table lookups use the unique index.
        sa.Index("ix_reservations_date_time", "reservation_date", "reservation_time"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    # The owner is always the authenticated account that booked it.
    user_id: Mapped[int] = mapped_column(sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False, index=True)
    table_id: Mapped[int] = mapped_column(sa.ForeignKey("restaurant_tables.id", ondelete="RESTRICT"), nullable=False)
    reservation_date: Mapped[date] = mapped_column(sa.Date, nullable=False)
    reservation_time: Mapped[time] = mapped_column(sa.Time, nullable=False)
    guest_count: Mapped[int] = mapped_column(sa.Integer, nullable=False)
    status: Mapped[ReservationStatus] = mapped_column(
        enum_column(ReservationStatus, 16, name="ck_reservations_status"),
        nullable=False,
        server_default=ReservationStatus.CONFIRMED.value,
    )
    holds_slot: Mapped[bool | None] = mapped_column(sa.Boolean, nullable=True, default=True)

    reserved_at: Mapped[datetime] = mapped_column(sa.DateTime, server_default=sa.func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False
    )

    user: Mapped["User"] = relationship()  # noqa: F821
    table: Mapped["RestaurantTable"] = relationship()  # noqa: F821

    def __repr__(self) -> str:  # pragma: no cover - debug aid only
        return f"<Reservation id={self.id} table_id={self.table_id} {self.reservation_date} {self.reservation_time}>"
